export const dataWorldCurrency = [['Country', 'Waluta'],
    ['Albania ', { v: 1, f: 'lek (ALL)' }],
    ['Andora', { v: 2, f: 'diner (ADD)' }],
    ['Austria ', { v: 3, f: 'euro (EUR)' }],
    ['Belgia', { v: 4, f: 'euro (EUR)' }],
    ['Białoruś ', { v: 5, f: 'rubel (BYR)' }],
    ['Bośnia i Hercegowina ', { v: 6, f: ' marka transferowa (BAM)' }],
    ['Bułgaria', { v: 7, f: 'lew (BGN)' }],
    ['Chorwacja ', { v: 8, f: 'kuna (HRK)' }],
    ['Czarnogóra', { v: 9, f: 'euro (EUR)' }],
    ['Czechy', { v: 0, f: 'korona czeska (CZK)' }],
    ['Dania', { v: 1, f: 'korona duńska (DKK)' }],
    ['Estonia', { v: 2, f: 'euro (EUR)' }],
    ['Finlandia', { v: 3, f: 'euro (EUR)' }],
    ['Francja', { v: 4, f: 'euro (EUR)' }],
    ['Grecja', { v: 5, f: 'euro (EUR)' }],
    ['Hiszpania', { v: 6, f: 'euro (EUR)' }],
    ['Holandia', { v: 7, f: 'euro  (EUR)' }],
    ['Irlandia', { v: 8, f: 'euro (EUR)' }],
    ['Islandia', { v: 9, f: 'korona islandzka  (ISK)' }],
    ['Hiszpania', { v: 0, f: 'euro (EUR)' }],
    ['Kosowo', { v: 1, f: 'euro (WAL)' }],
    ['Liechtenstein', { v: 2, f: 'frank szwajcarski (CHF)' }],
    ['Litwa', { v: 3, f: 'euro (EUR)' }],
    ['Luksemburg', { v: 4, f: 'euro (EUR)' }],
    ['Łotwa', { v: 5, f: 'euro  (EUR)' }],
    ['Macedonia', { v: 6, f: 'denar macedoński (MKD)' }],
    ['Malta', { v: 7, f: 'euro (EUR)' }],
    ['Mołdawia', { v: 8, f: 'lej mołdawski (MDL)' }],
    ['Monako', { v: 9, f: 'euro (EUR)' }],
    ['Niemcy', { v: 0, f: ' euro (EUR)' }],
    ['Norwegia', { v: 1, f: 'korona norweska (NOK)' }],
    ['Polska', { v: 9, f: 'złoty (PLN)' }],
    ['Portugalia', { v: 2, f: 'euro (EUR)' }],
    ['Rosja', { v: 3, f: 'rubel (RUB)' }],
    ['Rumunia', { v: 4, f: 'lej (RON)' }],
    ['San Marino', { v: 5, f: 'euro (EUR)' }],
    ['Serbia', { v: 6, f: 'dinar serbski (CSD)' }],
    ['Słowacja', { v: 7, f: 'euro (EUR)' }],
    ['Słowenia', { v: 8, f: 'euro (EUR)' }],
    ['Szwajcaria', { v: 9, f: 'frank szwajcarski (CHF)' }],
    ['Szwecja ', { v: 0, f: 'frank szwajcarski (SEK)' }],
    ['Ukraina', { v: 1, f: 'hrywna (UAH)' }],
    ['Węgry', { v: 2, f: ' forint (HUF)' }],
    ['Wielka Brytania', { v: 3, f: 'funt szterling (GBP)' }],
    ['Włochy', { v: 4, f: 'euro (EUR)' }],

    ['Afganistan', { v: 5, f: 'fgani (AFN)' }],
    ['Arabia Saudyjska', { v: 6, f: 'rial saudyjski (SAR)' }],
    ['Armenia', { v: 7, f: 'dram (AMD)' }],
    ['Azerbejdżan', { v: 8, f: 'manat (AZM)' }],
    ['Bahrajn', { v: 9, f: 'dinar Bahrajnu (BHD)' }],
    ['Bangladesz', { v: 0, f: 'taka bengalska (BDT)' }],
    ['Bhutan', { v: 1, f: 'ngultrum (BTN)' }],
    ['Brunei', { v: 2, f: 'dolar Brunei (BND)' }],
    ['Chiny', { v: 6, f: 'yuan (CNY)' }],
    ['Cypr', { v: 4, f: 'euro (EUR)' }],
    ['Filipiny', { v: 5, f: 'peso filipińskie (PHP)' }],
    ['Gruzja', { v: 6, f: 'lari (GEL)' }],
    ['Indie', { v: 7, f: 'rupia indyjska (INR)' }],
    ['Indonezja', { v: 8, f: 'rupia indonezyjska (IDR)' }],
    ['Irak', { v: 9, f: 'dinar iracki (IQD)' }],
    ['Iran', { v: 0, f: 'rial (IRR)' }],
    ['Izrael', { v: 1, f: 'szekel (ILS)' }],
    ['Japonia', { v: 2, f: 'jen (JPY)' }],
    ['Jemen', { v: 3, f: 'rial jemeński (YER)' }],
    ['Jordania', { v: 4, f: 'dinar jordański (JOD)' }],
    ['Kambodża', { v: 5, f: ' riel kambodżański (KHR)' }],
    ['Katar', { v: 6, f: 'rial Kataru (QAR)' }],
    ['Kazachstan', { v: 7, f: 'tenge (KZT)' }],
    ['Kirgistan', { v: 8, f: 'som (KGS)' }],
    ['Korea Południowa', { v: 9, f: 'won południowokoreański (KRW)' }],
    ['Korea Północna', { v: 0, f: 'won północnokoreański (KPW)' }],
    ['Kuwejt', { v: 1, f: 'dinar kuwejcki (KWD)' }],
    ['Laos', { v: 2, f: 'kip (LAK)' }],
    ['Liban', { v: 3, f: 'funt libański (LBP)' }],
    ['Malediwy', { v: 4, f: 'rupia malediwska (MVR)' }],
    ['Malezja', { v: 5, f: 'ringgit (MYR)' }],
    ['Mjanma', { v: 6, f: 'kiat (MMK)' }],
    ['Mongolia', { v: 7, f: 'tugrik (MNT)' }],
    ['Nepal', { v: 8, f: 'rupia nepalska (NPR)' }],
    ['Oman', { v: 9, f: 'rial (OMR)' }],
    ['Pakistan', { v: 0, f: 'rupia pakistańska (PKR)' }],
    ['Singapur', { v: 1, f: 'dolar singapurski (SGD)' }],
    ['Sri Lanka', { v: 2, f: 'rupia lankijska (LKR)' }],
    ['Syria', { v: 3, f: 'unt syryjski (SYP)' }],
    ['Tadżykistan', { v: 4, f: 'somoni (TJS)' }],
    ['Tajlandia', { v: 5, f: 'baht (THB)' }],
    ['Tajwan', { v: 6, f: 'dolar tajwański (TWD)' }],
    ['Timor Wschodni', { v: 7, f: 'dolar amerykański (USD)' }],
    ['Turcja', { v: 8, f: 'lira turecka (WAL)' }],
    ['Turkmenistan', { v: 9, f: 'manat turkmeński (TMM)' }],
    ['Uzbekistan', { v: 0, f: 'sum (UZS)' }],
    ['Wietnam', { v: 1, f: 'đồng (VND)' }],
    ['Zjednoczone Emiraty Arabskie', { v: 2, f: 'dirham (AED)' }],

    ['Antigua i Barbuda', { v: 3, f: 'dolar wschodniokaraibski (XCD)' }],
    ['Argentyna', { v: 4, f: 'peso argentyńskie (ARS)' }],
    ['Bahamy', { v: 5, f: 'dolar bahamski (BSD)' }],
    ['Barbados', { v: 6, f: 'dolar Barbadosu (BBD)' }],
    ['Belize', { v: 7, f: 'dolar Belize (BZD)' }],
    ['Boliwia', { v: 8, f: 'boliviano (peso boliwijskie) (BOB)' }],
    ['Brazylia', { v: 9, f: 'real (BRL)' }],
    ['Chile', { v: 0, f: ' peso chilijskie (CLP)' }],
    ['Dominika', { v: 1, f: 'dolar wschodniokaraibski (XCD)' }],
    ['Dominikana', { v: 2, f: 'peso dominikańskie (DOP)' }],
    ['Ekwador', { v: 3, f: 'dolar amerykański (USD)' }],
    ['Grenada', { v: 4, f: 'dolar wschodniokaraibski (XCD)' }],
    ['Gujana', { v: 5, f: 'dolar gujański (GYD)' }],
    ['Gwatemala', { v: 6, f: 'quetzal (GTQ)' }],
    ['Haiti', { v: 7, f: 'gourde (HTG)' }],
    ['Honduras', { v: 8, f: 'empira (HNL)' }],
    ['Jamajka', { v: 9, f: 'dolar jamajski (JMD)' }],
    ['Kanada', { v: 0, f: 'dolar kanadyjski (CAD)' }],
    ['Kolumbia', { v: 1, f: 'peso kolumbijskie (COP)' }],
    ['Kostaryka', { v: 2, f: 'colon (CRC)' }],
    ['Kuba', { v: 3, f: ' peso kubańskie (CUP)' }],
    ['Meksyk', { v: 4, f: 'peso meksykańskie (MXN)' }],
    ['Nikaragua', { v: 5, f: 'złota cordoba (NIO)' }],
    ['Panama', { v: 6, f: 'balboa (PAB)' }],
    ['Paragwaj', { v: 7, f: 'guarani (PYG)' }],
    ['Peru', { v: 8, f: 'sol (PEN)' }],
    ['Saint Kitts i Nevis', { v: 9, f: 'dolar wschodniokaraibski (XCD)' }],
    ['Saint Lucia', { v: 0, f: 'dolar wschodniokaraibski (XCD)' }],
    ['Saint Vincent i Grenadyny', { v: 1, f: 'dolar wschodniokaraibski (XCD)' }],
    ['Salwador', { v: 2, f: 'dolar amerykański (USD)' }],
    ['Stany Zjednoczone', { v: 3, f: 'dolar amerykański (USD)' }],
    ['Surinam', { v: 4, f: 'dolar surinamski (SRD)' }],
    ['Trynidad i Tobago', { v: 5, f: 'dolar Trynidadu i Tobago (TTD)' }],
    ['Urugwaj', { v: 6, f: 'peso urugwajskie (UYU)' }],
    ['Wenezuela', { v: 7, f: 'bolivar (VEB)' }],

    ['Australia', { v: 8, f: 'dolar australijski (AUD)' }],
    ['Federacja Mikronezji', { v: 9, f: 'dolar USA (USD)' }],
    ['Fidżi', { v: 0, f: 'dolar Fidżi' }],
    ['Kiribati', { v: 1, f: 'dolar australijski (AUD)' }],
    ['Nauru', { v: 2, f: 'dolar australijski (AUD)' }],
    ['Nowa Zelandia', { v: 3, f: 'dolar nowozelandzki' }],
    ['Palau', { v: 4, f: 'dolar USA (USD)' }],
    ['Papua-Nowa Gwinea', { v: 5, f: 'kina' }],
    ['Samoa Zachodnie', { v: 6, f: 'tala' }],
    ['Tonga', { v: 7, f: 'pa’anga' }],
    ['Tuvalu', { v: 8, f: ' dolar australijski (AUD)' }],
    ['Vanuatu', { v: 9, f: 'vatu' }],
    ['Wyspy Marshalla', { v: 0, f: 'dolar USA (USD)' }],
    ['Wyspy Salomona', { v: 1, f: 'dolar Wysp Salomona' }],

    ['Algieria', { v: 2, f: 'dinar algierski (DZD)' }],
    ['Angola', { v: 3, f: 'kwanza (AOA)' }],
    ['Benin', { v: 4, f: 'frank CFA (XOF)' }],
    ['Botswana', { v: 5, f: 'pula (BWP)' }],
    ['Burkina Faso', { v: 6, f: 'frank CFA (XOF)' }],
    ['Burundi', { v: 7, f: 'frank burundyjski (BIF)' }],
    ['Czad', { v: 8, f: 'frank CFA (XAF)' }],
    ['Demokratyczna Republika Konga', { v: 9, f: ' frank kongijski (CDF)' }],
    ['Dżibuti', { v: 0, f: 'frank dżibutyjski (DJF)' }],
    ['Egipt', { v: 1, f: 'unt egipski (EGP)' }],
    ['Erytrea', { v: 2, f: 'nakfa (ERN)' }],
    ['Etiopia', { v: 3, f: 'birr (ETB)' }],
    ['Gabon', { v: 4, f: 'frank CFA (XAF)' }],
    ['Gambia', { v: 5, f: 'dalasi (GMD)' }],
    ['Ghana', { v: 6, f: 'cedi (GHC)' }],
    ['Gwinea Równikowa', { v: 7, f: 'frank CFA (XAF)' }],
    ['Gwinea', { v: 8, f: 'frank gwinejski (GNF)' }],
    ['Gwinea Bissau', { v: 9, f: 'rank CFA (XOF)' }],
    ['Kamerun', { v: 0, f: ' frank CFA (XAF)' }],
    ['Kenia', { v: 1, f: 'szyling kenijski (KES)' }],
    ['Komory', { v: 2, f: 'frank CFA (KMF)' }],
    ['Kongo', { v: 3, f: 'frank CFA (XAF)' }],
    ['Lesotho', { v: 4, f: 'loti (LSL)' }],
    ['Liberia', { v: 5, f: 'dolar liberyjski (LRD)' }],
    ['Libia', { v: 6, f: 'dinar libijski (LYD)' }],
    ['Madagaskar', { v: 7, f: 'ariary (MGA)' }],
    ['Malawi', { v: 8, f: 'kwacha (MWK)' }],
    ['Mali', { v: 9, f: 'rank CFA (XOF)' }],
    ['Maroko', { v: 0, f: 'dirham (MAD)' }],
    ['Mauretania', { v: 1, f: 'ouguiya (MRO)' }],
    ['Mauritius', { v: 2, f: 'rupia maurytyjska (MUR)' }],
    ['Mozambik', { v: 3, f: 'metical (MZM)' }],
    ['Namibia', { v: 4, f: 'dolar namibijski (NAD)' }],
    ['Niger', { v: 5, f: 'frank CFA (XOF)' }],
    ['Nigeria', { v: 6, f: 'naira (NGN)' }],
    ['Południowa Afryka', { v: 7, f: 'rand (ZAR)' }],
    ['Republika Środkowoafrykańska', { v: 8, f: 'frank CFA (XAF)' }],
    ['Republika Zielonego Przylądka', { v: 9, f: 'escudo (CVE)' }],
    ['Rwanda', { v: 0, f: 'frank rwandyjski (RWF)' }],
    ['Senegal', { v: 1, f: 'frank CFA (XOF)' }],
    ['Seszele', { v: 2, f: 'rupia seszelska (SCR)' }],
    ['Sierra Leone', { v: 3, f: 'leone (SLL)' }],
    ['Somalia', { v: 4, f: 'szyling somalijski (SOS)' }],
    ['Suazi', { v: 5, f: 'lilangeni (SZL)' }],
    ['Sudan', { v: 6, f: 'funt sudański (SDG)' }],
    ['Sudan Południowy', { v: 7, f: 'funt południowosudański (SSP)' }],
    ['Tanzania', { v: 8, f: 'szyling tanzański (TZS)' }],
    ['Togo', { v: 9, f: 'frank CFA (XOF)' }],
    ['Tunezja', { v: 0, f: 'dinar tunezyjski (TND)' }],
    ['Uganda', { v: 1, f: 'szyling ugandyjski (UGX)' }],
    ['Wybrzeże Kości Słoniowej', { v: 2, f: 'frank CFA (XOF)' }],
    ['Wyspy Świętego Tomasza i Książęca', { v: 3, f: 'dobra (STD)' }],
    ['Zambia', { v: 4, f: 'kwacha (ZMK)' }],
    ['Zimbabwe', { v: 5, f: 'dolar Zimbabwe (ZWD)' }],

];
