export const dataWorldCurrency = [['Country', 'Waluta'],
    ['Albania ', { v: 5, f: 'lek (ALL)' }],
    ['Andora', { v: 5, f: 'diner (ADD)' }],
    ['Austria ', { v: 5, f: 'euro (EUR)' }],
    ['Belgia', { v: 5, f: 'euro (EUR)' }],
    ['Białoruś ', { v: 5, f: 'rubel (BYR)' }],
    ['Bośnia i Hercegowina ', { v: 5, f: ' marka transferowa (BAM)' }],
    ['Bułgaria', { v: 5, f: 'lew (BGN)' }],
    ['Chorwacja ', { v: 5, f: 'kuna (HRK)' }],
    ['Czarnogóra', { v: 5, f: 'euro (EUR)' }],
    ['Czechy', { v: 5, f: 'korona czeska (CZK)' }],
    ['Dania', { v: 5, f: 'korona duńska (DKK)' }],
    ['Estonia', { v: 5, f: 'euro (EUR)' }],
    ['Finlandia', { v: 5, f: 'euro (EUR)' }],
    ['Francja', { v: 5, f: 'euro (EUR)' }],
    ['Grecja', { v: 5, f: 'euro (EUR)' }],
    ['Hiszpania', { v: 5, f: 'euro (EUR)' }],
    ['Holandia', { v: 5, f: 'euro  (EUR)' }],
    ['Irlandia', { v: 5, f: 'euro (EUR)' }],
    ['Islandia', { v: 5, f: 'korona islandzka  (ISK)' }],
    ['Hiszpania', { v: 5, f: 'euro (EUR)' }],
    ['Kosowo', { v: 5, f: 'euro (WAL)' }],
    ['Liechtenstein', { v: 5, f: 'frank szwajcarski (CHF)' }],
    ['Litwa', { v: 5, f: 'euro (EUR)' }],
    ['Luksemburg', { v: 5, f: 'euro (EUR)' }],
    ['Łotwa', { v: 5, f: 'euro  (EUR)' }],
    ['Macedonia', { v: 5, f: 'denar macedoński (MKD)' }],
    ['Malta', { v: 5, f: 'euro (EUR)' }],
    ['Mołdawia', { v: 5, f: 'lej mołdawski (MDL)' }],
    ['Monako', { v: 5, f: 'euro (EUR)' }],
    ['Niemcy', { v: 5, f: ' euro (EUR)' }],
    ['Norwegia', { v: 5, f: 'korona norweska (NOK)' }],
    ['Polska', { v: 5, f: 'złoty (PLN)' }],
    ['Portugalia', { v: 5, f: 'euro (EUR)' }],
    ['Rosja', { v: 5, f: 'rubel (RUB)' }],
    ['Rumunia', { v: 5, f: 'lej (RON)' }],
    ['San Marino', { v: 5, f: 'euro (EUR)' }],
    ['Serbia', { v: 5, f: 'dinar serbski (CSD)' }],
    ['Słowacja', { v: 5, f: 'euro (EUR)' }],
    ['Słowenia', { v: 5, f: 'euro (EUR)' }],
    ['Szwajcaria', { v: 5, f: 'frank szwajcarski (CHF)' }],
    ['Szwecja ', { v: 5, f: 'frank szwajcarski (SEK)' }],
    ['Ukraina', { v: 5, f: 'hrywna (UAH)' }],
    ['Węgry', { v: 5, f: ' forint (HUF)' }],
    ['Wielka Brytania', { v: 5, f: 'funt szterling (GBP)' }],
    ['Włochy', { v: 5, f: 'euro (EUR)' }],

    ['Afganistan', { v: 5, f: 'fgani (AFN)' }],
    ['Arabia Saudyjska', { v: 5, f: 'rial saudyjski (SAR)' }],
    ['Armenia', { v: 5, f: 'dram (AMD)' }],
    ['Azerbejdżan', { v: 5, f: 'manat (AZM)' }],
    ['Bahrajn', { v: 5, f: 'dinar Bahrajnu (BHD)' }],
    ['Bangladesz', { v: 5, f: 'taka bengalska (BDT)' }],
    ['Bhutan', { v: 5, f: 'ngultrum (BTN)' }],
    ['Brunei', { v: 5, f: 'dolar Brunei (BND)' }],
    ['Chiny', { v: 5, f: 'yuan (CNY)' }],
    ['Cypr', { v: 5, f: 'euro (EUR)' }],
    ['Filipiny', { v: 5, f: 'peso filipińskie (PHP)' }],
    ['Gruzja', { v: 5, f: 'lari (GEL)' }],
    ['Indie', { v: 5, f: 'rupia indyjska (INR)' }],
    ['Indonezja', { v: 5, f: 'rupia indonezyjska (IDR)' }],
    ['Francja', { v: 5, f: 'tooltip (WAL)' }],
    ['Francja', { v: 5, f: 'tooltip (WAL)' }],
    ['Francja', { v: 5, f: 'tooltip (WAL)' }],
    ['Francja', { v: 5, f: 'tooltip (WAL)' }],
    ['Francja', { v: 5, f: 'tooltip (WAL)' }],
    ['Francja', { v: 5, f: 'tooltip (WAL)' }],
    ['Francja', { v: 5, f: 'tooltip (WAL)' }],
    ['Francja', { v: 5, f: 'tooltip (WAL)' }],
    ['Francja', { v: 5, f: 'tooltip (WAL)' }],
    ['Francja', { v: 5, f: 'tooltip (WAL)' }],
    ['Francja', { v: 5, f: 'tooltip (WAL)' }],


];
