export const dataWorldCurrency = [['Country', 'Waluta'],
    ['Albania', { v: 1, f: 'lek (ALL)' }],
    ['Andorra', { v: 2, f: 'diner (ADD)' }],
    ['Austria ', { v: 3, f: 'euro (EUR)' }],
    ['Belgium', { v: 4, f: 'euro (EUR)' }],
    ['Belarus', { v: 5, f: 'rubel (BYR)' }],
    ['Bosnia and Herzegovina', { v: 6, f: ' marka transferowa (BAM)' }],
    ['Bulgaria', { v: 7, f: 'lew (BGN)' }],
    ['Croatia', { v: 8, f: 'kuna (HRK)' }],
    ['Montenegro', { v: 9, f: 'euro (EUR)' }],
    ['Czech Republic', { v: 0, f: 'korona czeska (CZK)' }],
    ['Denmark', { v: 1, f: 'korona duńska (DKK)' }],
    ['Estonia', { v: 2, f: 'euro (EUR)' }],
    ['Finland', { v: 3, f: 'euro (EUR)' }],
    ['France', { v: 4, f: 'euro (EUR)' }],
    ['Greece', { v: 5, f: 'euro (EUR)' }],
    ['Spain', { v: 6, f: 'euro (EUR)' }],
    ['Netherlands', { v: 7, f: 'euro  (EUR)' }],
    ['Ireland', { v: 8, f: 'euro (EUR)' }],
    ['Iceland', { v: 9, f: 'korona islandzka  (ISK)' }],
    ['Kosovo', { v: 1, f: 'euro (WAL)' }],
    ['Liechtenstein', { v: 2, f: 'frank szwajcarski (CHF)' }],
    ['Lithuania', { v: 3, f: 'euro (EUR)' }],
    ['Luxembourg', { v: 4, f: 'euro (EUR)' }],
    ['Latvia', { v: 5, f: 'euro  (EUR)' }],
    ['Macedonia', { v: 6, f: 'denar macedoński (MKD)' }],
    ['Malta', { v: 7, f: 'euro (EUR)' }],
    ['Moldova', { v: 8, f: 'lej mołdawski (MDL)' }],
    ['Monaco', { v: 9, f: 'euro (EUR)' }],
    ['Germany', { v: 0, f: ' euro (EUR)' }],
    ['Norway', { v: 1, f: 'korona norweska (NOK)' }],
    ['Poland', { v: 9, f: 'złoty (PLN)' }],
    ['Portugal', { v: 2, f: 'euro (EUR)' }],
    ['Russia', { v: 3, f: 'rubel (RUB)' }],
    ['Romania', { v: 4, f: 'lej (RON)' }],
    ['San Marino', { v: 5, f: 'euro (EUR)' }],
    ['Serbia', { v: 6, f: 'dinar serbski (CSD)' }],
    ['Slovakia', { v: 7, f: 'euro (EUR)' }],
    ['Slovenia', { v: 8, f: 'euro (EUR)' }],
    ['Switzerland', { v: 9, f: 'frank szwajcarski (CHF)' }],
    ['Sweden', { v: 0, f: 'korona szwedzka (SEK)' }],
    ['Ukraine', { v: 1, f: 'hrywna (UAH)' }],
    ['Hungary', { v: 2, f: ' forint (HUF)' }],
    ['United Kingdom', { v: 3, f: 'funt szterling (GBP)' }],
    ['Italy', { v: 4, f: 'euro (EUR)' }],

    ['Afghanistan', { v: 5, f: 'fgani (AFN)' }],
    ['Saudi Arabia', { v: 6, f: 'rial saudyjski (SAR)' }],
    ['Armenia', { v: 7, f: 'dram (AMD)' }],
    ['Azerbaijan', { v: 8, f: 'manat (AZM)' }],
    ['Bahrain', { v: 9, f: 'dinar Bahrajnu (BHD)' }],
    ['Bangladesh', { v: 0, f: 'taka bengalska (BDT)' }],
    ['Bhutan', { v: 1, f: 'ngultrum (BTN)' }],
    ['Brunei', { v: 2, f: 'dolar Brunei (BND)' }],
    ['China', { v: 6, f: 'yuan (CNY)' }],
    ['Cyprus', { v: 4, f: 'euro (EUR)' }],
    ['Philippines', { v: 5, f: 'peso filipińskie (PHP)' }],
    ['Georgia', { v: 6, f: 'lari (GEL)' }],
    ['India', { v: 7, f: 'rupia indyjska (INR)' }],
    ['Indonesia', { v: 8, f: 'rupia indonezyjska (IDR)' }],
    ['Iraq', { v: 9, f: 'dinar iracki (IQD)' }],
    ['Iran', { v: 0, f: 'rial (IRR)' }],
    ['Israel', { v: 1, f: 'szekel (ILS)' }],
    ['Japan', { v: 2, f: 'jen (JPY)' }],
    ['Yemen', { v: 3, f: 'rial jemeński (YER)' }],
    ['Jordan', { v: 4, f: 'dinar jordański (JOD)' }],
    ['Cambodia', { v: 5, f: ' riel kambodżański (KHR)' }],
    ['Qatar', { v: 6, f: 'rial Kataru (QAR)' }],
    ['Kazakhstan', { v: 7, f: 'tenge (KZT)' }],
    ['Kyrgyzstan', { v: 8, f: 'som (KGS)' }],
    ['South Korea', { v: 9, f: 'won południowokoreański (KRW)' }],
    ['North Korea', { v: 0, f: 'won północnokoreański (KPW)' }],
    ['Kuwait', { v: 1, f: 'dinar kuwejcki (KWD)' }],
    ['Laos', { v: 2, f: 'kip (LAK)' }],
    ['Lebanon', { v: 3, f: 'funt libański (LBP)' }],
    ['Maldives', { v: 4, f: 'rupia malediwska (MVR)' }],
    ['Malaysia', { v: 5, f: 'ringgit (MYR)' }],
    ['Myanmar', { v: 6, f: 'kiat (MMK)' }],
    ['Mongolia', { v: 7, f: 'tugrik (MNT)' }],
    ['Nepal', { v: 8, f: 'rupia nepalska (NPR)' }],
    ['Oman', { v: 9, f: 'rial (OMR)' }],
    ['Pakistan', { v: 0, f: 'rupia pakistańska (PKR)' }],
    ['Singapore', { v: 1, f: 'dolar singapurski (SGD)' }],
    ['Sri Lanka', { v: 2, f: 'rupia lankijska (LKR)' }],
    ['Syria', { v: 3, f: 'unt syryjski (SYP)' }],
    ['Tajikistan', { v: 4, f: 'somoni (TJS)' }],
    ['Thailand', { v: 5, f: 'baht (THB)' }],
    ['Taiwan', { v: 6, f: 'dolar tajwański (TWD)' }],
    ['East Timor', { v: 7, f: 'dolar amerykański (USD)' }],
    ['Turkey', { v: 8, f: 'lira turecka (WAL)' }],
    ['Turkmenistan', { v: 9, f: 'manat turkmeński (TMM)' }],
    ['Uzbekistan', { v: 0, f: 'sum (UZS)' }],
    ['Vietnam', { v: 1, f: 'đồng (VND)' }],
    ['United Arab Emirates', { v: 2, f: 'dirham (AED)' }],

    ['Antigua and Barbuda', { v: 3, f: 'dolar wschodniokaraibski (XCD)' }],
    ['Argentina', { v: 4, f: 'peso argentyńskie (ARS)' }],
    ['Bahamas', { v: 5, f: 'dolar bahamski (BSD)' }],
    ['Barbados', { v: 6, f: 'dolar Barbadosu (BBD)' }],
    ['Belize', { v: 7, f: 'dolar Belize (BZD)' }],
    ['Bolivia', { v: 8, f: 'boliviano (peso boliwijskie) (BOB)' }],
    ['Brazil', { v: 9, f: 'real (BRL)' }],
    ['Chile', { v: 0, f: ' peso chilijskie (CLP)' }],
    ['Dominica', { v: 1, f: 'dolar wschodniokaraibski (XCD)' }],
    ['Dominican Republic', { v: 2, f: 'peso dominikańskie (DOP)' }],
    ['Ecuador', { v: 3, f: 'dolar amerykański (USD)' }],
    ['Grenada', { v: 4, f: 'dolar wschodniokaraibski (XCD)' }],
    ['Guyana', { v: 5, f: 'dolar gujański (GYD)' }],
    ['Guatemala', { v: 6, f: 'quetzal (GTQ)' }],
    ['Haiti', { v: 7, f: 'gourde (HTG)' }],
    ['Honduras', { v: 8, f: 'empira (HNL)' }],
    ['Jamaica', { v: 9, f: 'dolar jamajski (JMD)' }],
    ['Canada', { v: 0, f: 'dolar kanadyjski (CAD)' }],
    ['Colombia', { v: 1, f: 'peso kolumbijskie (COP)' }],
    ['Costa Rica', { v: 2, f: 'colon (CRC)' }],
    ['Cuba', { v: 3, f: ' peso kubańskie (CUP)' }],
    ['Mexico', { v: 4, f: 'peso meksykańskie (MXN)' }],
    ['Nicaragua', { v: 5, f: 'złota cordoba (NIO)' }],
    ['Panama', { v: 6, f: 'balboa (PAB)' }],
    ['Paraguay', { v: 7, f: 'guarani (PYG)' }],
    ['Peru', { v: 8, f: 'sol (PEN)' }],
    ['Saint Kitts i Nevis', { v: 9, f: 'dolar wschodniokaraibski (XCD)' }],
    ['Saint Lucia', { v: 0, f: 'dolar wschodniokaraibski (XCD)' }],
    ['Saint Vincent and the Grenadines', { v: 1, f: 'dolar wschodniokaraibski (XCD)' }],
    ['El Salvador', { v: 2, f: 'dolar amerykański (USD)' }],
    ['United States', { v: 3, f: 'dolar amerykański (USD)' }],
    ['Suriname', { v: 4, f: 'dolar surinamski (SRD)' }],
    ['Trinidad and Tobago', { v: 5, f: 'dolar Trynidadu i Tobago (TTD)' }],
    ['Uruguay', { v: 6, f: 'peso urugwajskie (UYU)' }],
    ['Venezuela', { v: 7, f: 'bolivar (VEB)' }],

    ['Australia', { v: 8, f: 'dolar australijski (AUD)' }],
    ['Federation of Micronesia', { v: 9, f: 'dolar USA (USD)' }],
    ['Fiji', { v: 0, f: 'dolar Fidżi' }],
    ['Kiribati', { v: 1, f: 'dolar australijski (AUD)' }],
    ['Nauru', { v: 2, f: 'dolar australijski (AUD)' }],
    ['New Zealand', { v: 3, f: 'dolar nowozelandzki' }],
    ['Palau', { v: 4, f: 'dolar USA (USD)' }],
    ['Papua New Guinea', { v: 5, f: 'kina' }],
    ['Western Samoa', { v: 6, f: 'tala' }],
    ['Tonga', { v: 7, f: 'pa’anga' }],
    ['Tuvalu', { v: 8, f: ' dolar australijski (AUD)' }],
    ['Vanuatu', { v: 9, f: 'vatu' }],
    ['Marshall Islands', { v: 0, f: 'dolar USA (USD)' }],
    ['Solomon Islands', { v: 1, f: 'dolar Wysp Salomona' }],

    ['Algeria', { v: 2, f: 'dinar algierski (DZD)' }],
    ['Angola', { v: 3, f: 'kwanza (AOA)' }],
    ['Benin', { v: 4, f: 'frank CFA (XOF)' }],
    ['Botswana', { v: 5, f: 'pula (BWP)' }],
    ['Burkina Faso', { v: 6, f: 'frank CFA (XOF)' }],
    ['Burundi', { v: 7, f: 'frank burundyjski (BIF)' }],
    ['Chad', { v: 8, f: 'frank CFA (XAF)' }],
    ['Democratic Republic of the Congo', { v: 9, f: ' frank kongijski (CDF)' }],
    ['Djibouti', { v: 0, f: 'frank dżibutyjski (DJF)' }],
    ['Egypt', { v: 1, f: 'unt egipski (EGP)' }],
    ['Eritrea', { v: 2, f: 'nakfa (ERN)' }],
    ['Ethiopia', { v: 3, f: 'birr (ETB)' }],
    ['Gabon', { v: 4, f: 'frank CFA (XAF)' }],
    ['The Gambia', { v: 5, f: 'dalasi (GMD)' }],
    ['Ghana', { v: 6, f: 'cedi (GHC)' }],
    ['Equatorial Guinea', { v: 7, f: 'frank CFA (XAF)' }],
    ['Guinea', { v: 8, f: 'frank gwinejski (GNF)' }],
    ['Guinea-Bissau', { v: 9, f: 'rank CFA (XOF)' }],
    ['Cameroon', { v: 0, f: ' frank CFA (XAF)' }],
    ['Kenya', { v: 1, f: 'szyling kenijski (KES)' }],
    ['Comoros', { v: 2, f: 'frank CFA (KMF)' }],
    ['Republic of the Congo', { v: 3, f: 'frank CFA (XAF)' }],
    ['Lesotho', { v: 4, f: 'loti (LSL)' }],
    ['Livery', { v: 5, f: 'dolar liberyjski (LRD)' }],
    ['Libya', { v: 6, f: 'dinar libijski (LYD)' }],
    ['Madagascar', { v: 7, f: 'ariary (MGA)' }],
    ['Malawi', { v: 8, f: 'kwacha (MWK)' }],
    ['Mali', { v: 9, f: 'rank CFA (XOF)' }],
    ['Morocco', { v: 0, f: 'dirham (MAD)' }],
    ['Mauritania', { v: 1, f: 'ouguiya (MRO)' }],
    ['Mauritius', { v: 2, f: 'rupia maurytyjska (MUR)' }],
    ['Mozambique', { v: 3, f: 'metical (MZM)' }],
    ['Namibia', { v: 4, f: 'dolar namibijski (NAD)' }],
    ['Niger', { v: 5, f: 'frank CFA (XOF)' }],
    ['Nigeria', { v: 6, f: 'naira (NGN)' }],
    ['South Africa', { v: 7, f: 'rand (ZAR)' }],
    ['Central African Republic', { v: 8, f: 'frank CFA (XAF)' }],
    ['Cape Verde', { v: 9, f: 'escudo (CVE)' }],
    ['Rwanda', { v: 0, f: 'frank rwandyjski (RWF)' }],
    ['Senegal', { v: 1, f: 'frank CFA (XOF)' }],
    ['Seychelles', { v: 2, f: 'rupia seszelska (SCR)' }],
    ['Sierra Leone', { v: 3, f: 'leone (SLL)' }],
    ['Somalia', { v: 4, f: 'szyling somalijski (SOS)' }],
    ['Swaziland', { v: 5, f: 'lilangeni (SZL)' }],
    ['Sudan', { v: 6, f: 'funt sudański (SDG)' }],
    ['South Sudan', { v: 7, f: 'funt południowosudański (SSP)' }],
    ['Tanzania', { v: 8, f: 'szyling tanzański (TZS)' }],
    ['Togo', { v: 9, f: 'frank CFA (XOF)' }],
    ['Tunisia', { v: 0, f: 'dinar tunezyjski (TND)' }],
    ['Uganda', { v: 1, f: 'szyling ugandyjski (UGX)' }],
    ['Ivory Coast', { v: 2, f: 'frank CFA (XOF)' }],
    ['Sao Tome and Principe', { v: 3, f: 'dobra (STD)' }],
    ['Zambia', { v: 4, f: 'kwacha (ZMK)' }],
    ['Zimbabwe', { v: 5, f: 'dolar Zimbabwe (ZWD)' }],
];
